#!/bin/bash

usage()
{
    program=$(basename $0)
    cat <<EOF
Usage:
    $program [-h] [-n | --name <name>] [-- <chef-solo parameters>]

Options:
    -h, --help                 Show this help
    -n, --name <name>          LXC container's name
    -- <chef-solo parameters>  Any parameters to pass to the chef-solo
                               (e.g. '-l debug')

EOF
}

while [ "$#" -gt 0 ]
do
  case $1 in
    -h|--help)
        usage
        exit 0
        ;;
    -n|--name)
        name=$2
        shift 2
        ;;
    --)
        params=$@
        break
        ;;
    *)
        break
        ;;
  esac
done

if [ -z $name ] || [ ! -d /var/lib/lxc/${name} ]; then
  echo "You need to pass a valid name of a container"
  usage
  exit 1
fi

lxc-ssh -n $name -c "sudo /opt/chef/bin/chef-solo -c /etc/chef/solo.rb $params"

